<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.scijava</groupId>
		<artifactId>pom-scijava</artifactId>
		<version>43.0.0</version>
	</parent>

	<groupId>sc.fiji</groupId>
	<artifactId>scijava-context-test</artifactId>
	<version>1.0-SNAPSHOT</version>

	<name>Scijava Context Test</name>
	<description>
		The only purpose of this repo is to test a potential memory leak in scijava context
	</description>
	<url>https://github.com/BioImageTools/scijava-context-test</url>
	<inceptionYear>2026</inceptionYear>

	<licenses>
		<license>
			<name>Simplified BSD License</name>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<organization>
		<name>SciJava</name>
		<url>https://scijava.org/</url>
	</organization>

	<developers>
		<developer>
			<id>stefanhahmann</id>
			<name>Stefan Hahmann</name>
			<email>stefan.hahmann@tu-dresden.de</email>
			<organization>MPI CBG</organization>
			<organizationUrl>https://www.mpi-cbg.de/</organizationUrl>
			<roles>
				<role>lead</role>
				<role>developer</role>
				<role>reviewer</role>
				<role>maintainer</role>
			</roles>
		</developer>
	</developers>

	<contributors>
		<!-- NB: Need at least one element to override the parent. See: https://issues.apache.org/jira/browse/MNG-5220 -->
		<contributor>
			<name>None</name>
		</contributor>
	</contributors>

	<mailingLists>
		<mailingList>
			<name>Image.sc Forum</name>
			<archive>https://forum.image.sc/tag/scijava/</archive>
		</mailingList>
	</mailingLists>

	<!-- ====================================== -->

	<scm>
		<connection>scm:git:git://github.com/BioImageTools/scijava-context-test</connection>
		<developerConnection>scm:git:git@github.com:BioImageTools/scijava-context-test</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/BioImageTools/scijava-context-test</url>
	</scm>
	<issueManagement>
		<system>GitHub Issues</system>
		<url>https://github.com/BioImageTools/scijava-context-test/issues</url>
	</issueManagement>
	<ciManagement>
		<system>GitHub Actions</system>
		<url>https://github.com/BioImageTools/scijava-context-test</url>
	</ciManagement>

	<properties>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<license.licenseName>bsd_2</license.licenseName>
		<license.organizationName>SciJava</license.organizationName>
		<license.copyrightOwners>SciJava developers</license.copyrightOwners>
	</properties>

	<repositories>
		<repository>
			<id>scijava.public</id>
			<url>https://maven.scijava.org/content/groups/public</url>
		</repository>
	</repositories>

	<dependencies>
		<!-- include fiji -->
		<dependency>
			<groupId>sc.fiji</groupId>
			<artifactId>fiji</artifactId>
			<scope>test</scope>
			<exclusions>

				<!-- Fiji Is Just ImageJ! -->
				<exclusion>
					<groupId>net.imagej</groupId>
					<artifactId>imagej</artifactId>
				</exclusion>
				<exclusion>
					<groupId>net.imagej</groupId>
					<artifactId>ij</artifactId>
				</exclusion>
				<exclusion>
					<groupId>net.imagej</groupId>
					<artifactId>imagej-legacy</artifactId>
				</exclusion>

				<!-- Standard Fiji projects - https://github.com/fiji -->
				<exclusion>
					<groupId>org.janelia</groupId>
					<artifactId>H5J_Loader_Plugin</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>3D_Blob_Segmentation</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>3D_Objects_Counter</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>3D_Viewer</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>AnalyzeSkeleton_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Anisotropic_Diffusion_2D</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Archipelago_Plugins</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Arrow_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Auto_Local_Threshold</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Auto_Threshold</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>BalloonSegmentation_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Bug_Submitter</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>CPU_Meter</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Calculator_Plus</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Cell_Counter</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Colocalisation_Analysis</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Color_Histogram</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Color_Inspector_3D</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Colour_Deconvolution</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>CorrectBleach_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Correct_3D_Drift</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Descriptor_based_registration</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Dichromacy_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Directionality_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>FS_Align_TrakEM2</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Feature_Detection</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Fiji_Archipelago</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Fiji_Developer</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Fiji_Package_Maker</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Fiji_Plugins</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>FilamentDetector</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>FlowJ_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Graph_Cut</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Gray_Morphology</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>HDF5_Vibez</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Helmholtz_Analysis</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>IJ_Robot</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>IO_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Image_5D</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Image_Expression_Parser</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Interactive_3D_Surface_Plot</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>IsoData_Classifier</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Kappa</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Kuwahara_Filter</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>KymographBuilder</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>LSM_Reader</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>LSM_Toolbox</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Lasso_and_Blow_Tool</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Linear_Kuwahara</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>LocalThickness_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>MTrack2_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>M_I_P</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Manual_Tracking</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Multi_Kymograph</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>OMEVisual</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>PIV_analyser</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>QuickPALM_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>RATS_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Reconstruct_Reader</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>SPIM_Opener</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>SPIM_Registration</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Samples_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Series_Labeler</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Siox_Segmentation</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Skeletonize3D_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>SplineDeformationGenerator_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Stack_Manipulation</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Statistical_Region_Merging</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Stitching_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Sync_Win</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Thread_Killer</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Time_Lapse</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Time_Stamper</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>ToAST_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>TopoJ_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>TrackMate</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Trainable_Segmentation</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>TrakEM2_Archipelago</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>VIB-lib</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>VIB_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Vaa3d_Reader</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Vaa3d_Writer</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Video_Editing</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Volume_Calculator</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>Volume_Viewer</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>bUnwarpJ_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>blockmatching_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>fiji-lib</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>legacy-imglib1</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>level_sets</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>pal-optimization</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>panorama_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>register_virtual_stack_slices</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>registration_3d</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>weave_jy2java</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>z_spacing</artifactId>
				</exclusion>

				<!-- External Fiji projects -->
				<!-- https://github.com/bionanoimaging/View5D -->
				<exclusion>
					<groupId>de.nanoimaging</groupId>
					<artifactId>View5D_</artifactId>
				</exclusion>
				<!-- https://github.com/saalfeldlab/jitk-tps -->
				<exclusion>
					<groupId>jitk</groupId>
					<artifactId>jitk-tps</artifactId>
				</exclusion>
				<!-- https://github.com/axtimwalde/mpicbg -->
				<exclusion>
					<groupId>mpicbg</groupId>
					<artifactId>mpicbg_</artifactId>
				</exclusion>
				<!-- https://github.com/openmicroscopy/bioformats -->
				<exclusion>
					<groupId>ome</groupId>
					<artifactId>bio-formats_plugins</artifactId>
				</exclusion>
				<!-- https://github.com/saalfeldlab/n5-viewer -->
				<exclusion>
					<groupId>org.janelia.saalfeldlab</groupId>
					<artifactId>n5-viewer_fiji</artifactId>
				</exclusion>
				<!-- https://github.com/saalfeldlab/bigwarp -->
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>bigwarp_fiji</artifactId>
				</exclusion>
				<!-- https://github.com/juglab/labkit-ui -->
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>labkit-ui</artifactId>
				</exclusion>
				<!-- https://github.com/saalfeldlab/trakem2-tps -->
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>trakem2_tps</artifactId>
				</exclusion>

				<!-- BigDataViewer projects - https://github.com/bigdataviewer -->
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>bigdataviewer-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>bigdataviewer-vistools</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>bigdataviewer_fiji</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>spim_data</artifactId>
				</exclusion>

				<!-- TrakEM2 projects - https://github.com/trakem2 -->
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>T2-NIT</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>T2-TreelineGraph</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>TrakEM2_</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>VectorString</artifactId>
				</exclusion>
				<exclusion>
					<groupId>sc.fiji</groupId>
					<artifactId>trakem2-transform</artifactId>
				</exclusion>

				<!-- SCIFIO projects - https://github.com/scifio -->
				<exclusion>
					<groupId>io.scif</groupId>
					<artifactId>scifio-bf-compat</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.scif</groupId>
					<artifactId>scifio-hdf5</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.scif</groupId>
					<artifactId>scifio-lifesci</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.scif</groupId>
					<artifactId>scifio-ome-xml</artifactId>
				</exclusion>


				<exclusion>
					<groupId>ch.qos.reload4j</groupId>
					<artifactId>reload4j</artifactId>
				</exclusion>

				<!-- JFreeSVG - https://www.jfree.org/jfreesvg/ -->
				<exclusion>
					<groupId>org.jfree</groupId>
					<artifactId>jfreesvg</artifactId>
				</exclusion>

				<!-- JOGL libraries, for Java 3D - https://github.com/jogamp -->
				<exclusion>
					<groupId>org.jogamp.gluegen</groupId>
					<artifactId>gluegen-rt</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jogamp.jogl</groupId>
					<artifactId>jogl-all</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jogamp.gluegen</groupId>
					<artifactId>gluegen-rt</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jogamp.jogl</groupId>
					<artifactId>jogl-all</artifactId>
				</exclusion>

				<!-- Optional runtime dependencies -->
				<exclusion>
					<groupId>org.scijava</groupId>
					<artifactId>scijava-config</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-classic</artifactId>
				</exclusion>
				<!-- Test scope dependencies -->
				<exclusion>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- only scijava-common -->
		<!--
		<dependency>
			<groupId>org.scijava</groupId>
			<artifactId>scijava-common</artifactId>
		</dependency>
		-->

		<!-- JUnit 5 - https://junit.org/junit5/ -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

</project>