<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.scijava</groupId>
		<artifactId>pom-scijava</artifactId>
		<version>43.0.0</version>
	</parent>

	<groupId>sc.fiji</groupId>
	<artifactId>scijava-context-test</artifactId>
	<version>1.0-SNAPSHOT</version>

	<name>Scijava Context Test</name>
	<description>
		The only purpose of this repo is to test a potential memory leak in scijava context
	</description>
	<url>https://github.com/BioImageTools/scijava-context-test</url>
	<inceptionYear>2026</inceptionYear>

	<licenses>
		<license>
			<name>Simplified BSD License</name>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<organization>
		<name>SciJava</name>
		<url>https://scijava.org/</url>
	</organization>

	<developers>
		<developer>
			<id>stefanhahmann</id>
			<name>Stefan Hahmann</name>
			<email>stefan.hahmann@tu-dresden.de</email>
			<organization>MPI CBG</organization>
			<organizationUrl>https://www.mpi-cbg.de/</organizationUrl>
			<roles>
				<role>lead</role>
				<role>developer</role>
				<role>reviewer</role>
				<role>maintainer</role>
			</roles>
		</developer>
	</developers>

	<contributors>
		<!-- NB: Need at least one element to override the parent. See: https://issues.apache.org/jira/browse/MNG-5220 -->
		<contributor>
			<name>None</name>
		</contributor>
	</contributors>

	<mailingLists>
		<mailingList>
			<name>Image.sc Forum</name>
			<archive>https://forum.image.sc/tag/scijava/</archive>
		</mailingList>
	</mailingLists>

	<!-- ====================================== -->

	<scm>
		<connection>scm:git:git://github.com/BioImageTools/scijava-context-test</connection>
		<developerConnection>scm:git:git@github.com:BioImageTools/scijava-context-test</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/BioImageTools/scijava-context-test</url>
	</scm>
	<issueManagement>
		<system>GitHub Issues</system>
		<url>https://github.com/BioImageTools/scijava-context-test/issues</url>
	</issueManagement>
	<ciManagement>
		<system>GitHub Actions</system>
		<url>https://github.com/BioImageTools/scijava-context-test</url>
	</ciManagement>

	<properties>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<license.licenseName>bsd_2</license.licenseName>
		<license.organizationName>SciJava</license.organizationName>
		<license.copyrightOwners>SciJava developers</license.copyrightOwners>
	</properties>

	<repositories>
		<repository>
			<id>scijava.public</id>
			<url>https://maven.scijava.org/content/groups/public</url>
		</repository>
	</repositories>

	<dependencies>
		<!-- include fiji -->
		<!--
		<dependency>
			<groupId>sc.fiji</groupId>
			<artifactId>fiji</artifactId>
			<scope>test</scope>
		</dependency>
		-->
		<!-- only scijava-common -->
		<dependency>
			<groupId>org.scijava</groupId>
			<artifactId>scijava-common</artifactId>
		</dependency>

		<!-- JUnit 5 - https://junit.org/junit5/ -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

</project>